apiVersion: apps/v1
kind: Deployment
metadata:
  name: easymoney-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easymoney-db
  template:
    metadata:
      labels:
        app: easymoney-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: easymoney_db
            - name: MYSQL_ROOT_PASSWORD
              value: e12345678E
          args:
            - "--default-authentication-plugin=mysql_native_password"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}