app:
  image: easymoney
  tag: latest
  port: 8080
  env:
    SPRING_DATASOURCE_URL: jdbc:mysql://easymoney-db:3306/easymoney_db
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: e12345678E
    SPRING_APPLICATION_NAME: easymoney
    SPRING_JPA_HIBERNATE_DDL_AUTO: update
    SPRING_JPA_SHOW_SQL: "true"
    SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    SPRING_PROFILES_ACTIVE: docker